PluginException: -fixed regression with stable -do not final the new VALUE_ID_PREMIUM_ONLY as the compiler will replace reference with value, breaks stable compatibility Flickr: added support for different account languages ShareOnline: -fixed freelimit -added support for overloaded servers Multi: -brought back the filename charset correction -updated fallback when filename could not be created on disk (modified charset, original charset, modified filename)